FROM adhi97/alpine-python3-base

MAINTAINER Adheesh Maheshwari <adhi97@gmail.com>

WORKDIR /app
RUN touch __init__.py
COPY user ./user
COPY util ./util

RUN pip3 install --upgrade pip && \
    cp user/nginx/default.conf /etc/nginx/conf.d/ && \
    mv user/requirements.txt . && \
    mv user/uwsgi.ini . && \
    pip3 install -r requirements.txt && \
    mkdir -p /var/run/ && \
    mkdir -p /run/nginx

EXPOSE 80
CMD ["user/docker/start.sh"]