FROM alpine:3.6

WORKDIR /app
RUN touch __init__.py
COPY user ./user
COPY util ./util

RUN apk add --no-cache \
        gcc \
        musl-dev \
        linux-headers \
        nginx \
        uwsgi \
        uwsgi-python3 \
        python3-dev \
        python3

RUN pip3 install --upgrade pip && \
    cp user/nginx/default.conf /etc/nginx/conf.d/ && \
    mv user/requirements.txt . && \
    mv user/uwsgi.ini . && \
    pip3 install -r requirements.txt && \
    mkdir -p /var/run/ && \
    mkdir -p /run/nginx

EXPOSE 80
CMD ["user/docker/start.sh"]